name: Continuos Integration
run-name: Proccess Git Push Request
on: [push]
jobs:
  Continuos-Integration:
    runs-on: windows-latest
    environment:
      name: Desenvolvimento

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Install Dependencies
        continue-on-error: true
        id: install-dependencies
        run: npm install

      - name: Execute tests
        continue-on-error: true
        id: testes
        run: npm run test

      - name: Execute build
        continue-on-error: true
        id: build
        run: npm run start

      - name: Criar Release
        id: create_release
        continue-on-error: true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: fals

      - name: Enviar Email
        if: steps.install-dependencies.outcome == 'failure' || steps.test.outcome == 'failure' || steps.build.outcome == 'failure' || steps.create_release.outcome == 'failure'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Falha no Pipeline de CI/CD - ${{ github.repository }} - ${{ github.run_id }}
          to: julio_soares_mendes@hotmail.com
          from: b4r7y@hotmail.com
          body: |
            O pipeline de CI/CD falhou na etapa "${{ steps.failed[0].name }}".
            Acesse o log para mais detalhes: ${{ runner.url }}/log/${{ github.run_id }}
