name: Continuos Integration
run-name: Proccess Git Push Request
on: [push]
jobs:
  Continuos-Integration:
    runs-on: windows-latest
    environment:
      name: Desenvolvimento

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.
      - name: Install Dependencies
        continue-on-error: true
        id: install-dependencies
        run: npm ci

      - name: Execute tests
        continue-on-error: true
        id: test
        run: npm run testes

      - name: Enviar Email
        if: steps.test.outcome == 'failure'
        uses: hilarion5/send-mail@v1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Falha no Pipeline de CI/CD - ${{ github.repository }} - ${{ github.run_id }}
          to: julio_soares_mendes@hotmail.com
          from: b4r7y@hotmail.com
          body: |
            O pipeline de CI/CD falhou na etapa "${{ steps.failed[0].name }}".
            Acesse o log para mais detalhes: ${{ runner.url }}/log/${{ github.run_id }}

      - name: Execute build
        continue-on-error: true
        id: build
        run: npm run start

      - name: Check Code
        continue-on-error: true
        id: check-code
        uses: actions/check-code@v2

      - name: Create Release
        id: create_release
        continue-on-error: true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release de ${{ github.ref_name }}
            - Testes: ${{ steps.test.outcome }}
            - Build: ${{ steps.build.outcome }}
            - Check Code: ${{ steps.check-code.outcome }}
          draft: false
          prerelease: fals

      - name: Anexar Artefato ao Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.github/workflows/artefato.zip
          asset_name: artefato.zip
          asset_content_type: application/zip

      - name: Enviar Email
        if: steps.install-dependencies.outcome == 'failure' || steps.test.outcome == 'failure' || steps.build.outcome == 'failure' || steps.create_release.outcome == 'failure'
        uses: hilarion5/send-mail@v1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Falha no Pipeline de CI/CD - ${{ github.repository }} - ${{ github.run_id }}
          to: julio_soares_mendes@hotmail.com
          from: b4r7y@hotmail.com
          body: |
            O pipeline de CI/CD falhou na etapa "${{ steps.failed[0].name }}".
            Acesse o log para mais detalhes: ${{ runner.url }}/log/${{ github.run_id }}
