name: Continuos Integration
run-name: Proccess Git Push Request
on: [push]
jobs:
  Continuos-Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Install Dependencies
        continue-on-error: true
        id: install-dependencies
        run: npm install
      - name: Execute tests
        continue-on-error: true
        id: test
        run: npm run testteste:integration
      - name: Execute build
        continue-on-error: true
        id: build
        run: npm run build

      - name: Create Release and Aprove
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Enviar Email
        if: steps.build.outcome == 'failure'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Erro no pipeline
          to: destinatario@example.com
          from: remetente@example.com
          body: Ocorreu um erro na execução do pipeline.
